# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Dùng Ubuntu 20.04 (focal)
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder ".", "/home/vagrant/my-vm"

  # Cấu hình mạng (có thể đổi IP nếu cần)
  config.vm.network "private_network", ip: "192.168.56.10"

  # Forward port từ VM ra Windows
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 3307, host: 3307

  # Tự động cài Docker & Docker Compose
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io

    # Thêm user vagrant vào group docker
    usermod -aG docker vagrant

    # Cài Docker Compose
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
      -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  SHELL
end
